group=org.yuemi
version=1.0.0-SNAPSHOT
paperApiVersion=1.21.6-R0.1-SNAPSHOT
artifactId=mc-config-libs
developerName=YueMi-Development
developerId=yuemi
repoUrl=https://github.com/YueMi-Development/MC-Config-Libs
yuemiMavenSnapshot=https://repo.yuemi.my.id/repository/maven-snapshots/
yuemiMavenRelease=https://repo.yuemi.my.id/repository/maven-releases/
