group=org.yuemi
version=1.0.0-SNAPSHOT
artifactId=mc-config-api
developerName=YueMi-Development
developerId=yuemi
repoUrl=https://github.com/YueMi-Development/mc-config-api
yuemiMavenSnapshot=https://repo.yuemi.my.id/repository/maven-snapshots/
yuemiMavenRelease=https://repo.yuemi.my.id/repository/maven-releases/
